### ISSUE TITLE
Julia and matlab scripts for the benchmarks results

### ISSUE THREAD

**Issue by ahsabali** [jondeuce/DECAES.jl#42]
Could you point to the julia and matlab scripts for the benchmarks results presented in the readme section [here](https://github.com/jondeuce/DECAES.jl#benchmarks)?

**Comment by jondeuce** [comment]
Unfortunately I don't have such scripts available for two reasons:

1. Those benchmarks were run using patient data which I am not able to share, and
2. The MATLAB code which DECAES.jl was based on was not developed by me and is not open-sourced. However, access to the MATLAB code can be requested from the [UBC MRI Research Centre website](https://mriresearch.med.ubc.ca/news-projects/myelin-water-fraction/)

With that being said, I should put together some similar benchmarks using the data from the [examples repository](https://github.com/jondeuce/mwiexamples). This would still require requesting the original MATLAB code from the above link in order to run them, though.
