### ISSUE TITLE
Incompatible with Julia v1.9.0

### ISSUE THREAD

**Issue by orie2409** [jondeuce/DECAES.jl#53]
Hi there,

You may already be working on this, but just to let you know that I get a hanging command line when I try and run your ./examples.sh file with Julia v1.9.0. It works when I switch to Julia v1.6.7.

Thanks

**Comment by jondeuce** [comment]
Thanks for the heads up! Yes, I noticed this when upgrading to v1.9 myself. I've fixed the issue on the master branch; will tag a new release shortly.

**Comment by jondeuce** [comment]
DECAES v0.5.0 is now tagged and should work with Julia v1.9+. I've noticed increased precompile time for some dependencies on v1.9.0 (e.g. `MathOptInterface`), but otherwise things look to be running smoothly.

I'll close this issue for now, but please feel free to ping me if you have further issues!
