### ISSUE TITLE
Intra and Extra-cellular water maps

### ISSUE THREAD

**Issue by ncbss** [jondeuce/DECAES.jl#63]
Hi there, 
Hope all is well

I am interested in analyzing differences in intra-and extra-cellular maps across diagnostic groups. I have checked the DECAES documentation and I am not quite sure how to extract these data. If you don’t mind my asking, is it possible to generate intra- and extra-cellular maps from GRASE images using DECAES? Or if these values are already part of the standard output, could you confirm what they are? 

I'd very much appreciate your help.
Thanks!

**Comment by jondeuce** [comment]
Do you mean separate maps of intracellular water fraction and extracellular water fraction? If so, this is not possible with DECAES because both pools have similar relaxation times and are therefore indistinguishable by DECAES. In fact, I'm not aware of any method that can disentangle these two water pools.

If you want the combined intra/extracellular water pool fraction (IEWF), then yes this is part of the standard output. Use the `MPWin` flag to set the range of T2 values (at 3T, [40ms, 200ms] is a typical IEWF range), and then the `mfr` field of the T2 parts output file corresponds to the IEWF.

`MPWin` stands for "medium pool window", analagous to `SPWin` which stands for "small pool window", and similarly `mfr` and `sfr` stand for medium/small pool water fraction. [See the docs here](https://jondeuce.github.io/DECAES.jl/dev/ref/#t2part) for more detailed descriptions of the command line flags and output arguments.

**Comment by ncbss** [comment]
I see, thank you for the details. That's very helpful.

**Comment by jondeuce** [comment]
No problem! Will close this issue now, but feel free to re-open if needed.
